### ISSUE TITLE
Update chart repository reference in dependencies files

### ISSUE THREAD

**Issue by tompizmor** [bitnami-labs/charts-syncer#100]
Currently, the dependencies are fetched from the target repository so the values.yaml files of the dependencies are already updated and point to the new container registry specified in the config file. So far so good.

However, the Chart.yaml and Chart.lock files for charts using API version 2 and requirements.yaml and requirements.lock files for charts using API version 1 are not updating the repository references.

So, for example, if source repo URL is `https://source.repo.url` and target repo URL is `https://target.repo.url`, we left the *.lock file as:

```
dependencies:
- name: zookeeper
  repository: https://source.repo.url
  version: 5.14.3
digest: sha256:2f3c43ce02e3966648b8c89be121fe39537f62ea1d161ad908f51ddc90e4243e
generated: "2020-05-11T07:41:53.934924625Z"
```

while it should be:

```
dependencies:
- name: zookeeper
  repository: https://target.repo.url
  version: 5.14.3
digest: NEW_DIGEST
generated: "2020-05-11T07:41:53.934924625Z"
```
