### ISSUE TITLE
Allow to specify container credentials

### ISSUE THREAD

**Issue by tompizmor** [bitnami-labs/charts-syncer#118]
Since charts-syncer can now work with relok8s lib we should be able to specify the credentials used to pull/push container images.

We could just add the next configuration section:

```
  containerAuth:
      host: 'docker.io'
      username: "USERNAME"
      password: "PASSWORD"
```

Example of use in config file:
```
source:
  repo:
    kind: HELM
    url: https://charts.app-catalog.vmware.com/demo
  containerAuth:
      host: 'docker.io'
      username: "SOURCE_DOCKER_REGISTRY_USERNAME"
      password: "SOURCE_DOCKER_REGISTRY_PASSWORD"
target:
  containerRegistry: northamerica-northeast1-docker.pkg.dev
  containerRepository: my-project/demo/containers
  containerAuth:
      host: 'docker.io'
      username: "TARGET_DOCKER_REGISTRY_USERNAME"
      password: "TARGET_DOCKER_REGISTRY_PASSWORD"
  repo:
    kind: OCI
    url: https://northamerica-northeast1-docker.pkg.dev/my-project/demo/charts
    auth:
      username: "TARGET_CHART_REPO_USERNAME"
      password: "TARGET_CHART_REPO_PASSWORD"
relocateContainerImages: true
```
