### ISSUE TITLE
Support Helm repositories with chart packages grouped in subfolders

### ISSUE THREAD

**Issue by tompizmor** [bitnami-labs/charts-syncer#21]
The tool assumes the chart .tgz is at REPO_URL/chart-package.tgz, however, there can be repos where the chart packages are actually at REPO_URL/chart/chart-package.tgz. Maybe there can be even other different paths.

Instead of assuming the URL for a chart-package.tgz, we should get it from the index.yaml. The download URL can be found under `urls`

```
wordpress:
  - apiVersion: v1
    appVersion: 5.4.2
    digest: 098b0c24edb73d4ac657bbf1b0b4aaafa05668618b9c86c1add608bcd769873.   
    ...
    urls:
    - https://charts.bitnami.com/bitnami/wordpress-9.3.15.tgz
    version: 9.3.15
```
