### ISSUE TITLE
UTF-8 octet causes error in pushing to repo

### ISSUE THREAD

**Issue by jamesdavismf** [bitnami-labs/charts-syncer#215]
Error syncing some charts from HELM to OCI repo - have seen with `kuberhealthy` being pulled from `https://kuberhealthy.github.io/kuberhealthy/helm-repos` and `kube-prometheus-stack` from `https://prometheus-community.github.io/helm-charts` 

`Error syncing charts: Failed to push Helm chart: failed to push Helm chart: cannot load values.yaml: error converting YAML to JSON: yaml: invalid trailing UTF-8 octet` 

Suspect that this is because a few characters within the values.yaml files, for example within the kuberhealthy values.yaml file contains `μ`

Sample config file: 

```YAML 
source:
  repo:
    kind: HELM
    url: https://kuberhealthy.github.io/kuberhealthy/helm-repos
target:
  repo: 
    kind: OCI
    url: oci://registry-1.docker.io/docker
charts:
  - kuberhealthy
```
