### ISSUE TITLE
Error: mkdir /.charts-syncer: permission denied

### ISSUE THREAD

**Issue by Sajfer** [bitnami-labs/charts-syncer#242]
### What steps will reproduce the bug?

Im trying to run the chart-syncer docker image to sync the keycloak chart but keep getting permission denied. I have tried with both the 2.1.1-debian-12-r4 and 2.1.1 docker images.

```
docker run --volume $(pwd)/config.yaml:/charts-syncer.yaml bitnami/charts-syncer:2.1.1-debian-12-r4 sync
 »  Syncing charts
Error: mkdir /.charts-syncer: permission denied
exit status 1
```

This is the configuration I was trying to use.
```
cat config.yaml
source:
  repo:
    kind: OCI
    url: https://registry-1.docker.io/bitnamicharts/
target:
  repo:
    kind: LOCAL
    path: /tmp/charts
charts:
  - keycloak
```

### What is the expected behavior?

The chart to be synced to the folder specified in the configuration.

### What do you see instead?

Error: mkdir /.charts-syncer: permission denied
