### ISSUE TITLE
Environment variables used to set auth doesn't work

### ISSUE THREAD

**Issue by carrodher** [bitnami-labs/charts-syncer#31]
I am trying to use the tool with a target repository that requires authentication. Using the yaml everything works as expected:
```yaml
target:
   auth:
     # username is the username used to authenticate against the target chart repo
     # `TARGET_AUTH_USERNAME` env var can be used instead of this entry
     username: "robot$chart-syncer"
     # password is the password used to authenticate against the target chart repo
     # `TARGET_AUTH_PASSWORD` env var can be used instead of this entry
     password: "somePasswrod"
```
but when using the env. variables (both `TARGET_AUTH_*` and `TARGET_REPO_*`) with the same values, the authentication doesn't work:
```
POST chart status Code: 401, Message: {"code":401,"message":"UnAuthorized"}
```
