### ISSUE TITLE
Properly update dependencies references when repository is OCI

### ISSUE THREAD

**Issue by tompizmor** [bitnami-labs/charts-syncer#81]
It seems dependencies from OCI repositories are now supported on Helm CLI since version 3.5.0. We should check in which status we left the dependencies file so they are compatible with the new version of Helm/

**Comment by tompizmor** [comment]
Right now after syncing a chart we left the dependencies section from Chart.yaml in the following state:

```
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
```

I've been testing the new version (helm 3.5.0) and the command `helm dependency update` works if it is like this:

```
dependencies:
- name: common
  repository: oci://demo.goharbor.io/tpmoci/charts-syncer/
  tags:
  - bitnami-common
  version: 1.2.3
```

So we now have to specify the exact version of the dependency. Is not a surprise since there is no index in OCI so helm cli is not able to resolve the dependency either.

----------

Proof of work:

```
$ helm dependency update      
                                                                                     
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "oci://demo.goharbor.io/tpmoci/charts-syncer" chart repository:
	tag explicitly required
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading common from repo oci://demo.goharbor.io/tpmoci/charts-syncer
1.2.3: Pulling from demo.goharbor.io/tpmoci/charts-syncer/common
Deleting outdated charts
```
